version: '3'
services:
  pve-connection:
    image: youmiepie/pve-connection:latest
    container_name: pve-connection
    restart: unless-stopped
    ports:
      - "80:8080"
    environment:
      - APP_DATA_DIR=/data
    volumes:
      - ./data:/data
